// Generated by gencpp from file styx_msgs/CarState.msg
// DO NOT EDIT!


#ifndef STYX_MSGS_MESSAGE_CARSTATE_H
#define STYX_MSGS_MESSAGE_CARSTATE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>

#include <std_msgs/Header.h>

namespace styx_msgs
{
template <class ContainerAllocator>
struct CarState_
{
  typedef CarState_<ContainerAllocator> Type;

  CarState_()
    : header()
    , position(0.0)
    , speed(0.0)
    , camera1d()  {
    }
  CarState_(const ContainerAllocator& _alloc)
    : header(_alloc)
    , position(0.0)
    , speed(0.0)
    , camera1d(_alloc)  {
  (void)_alloc;
    }



   typedef  ::std_msgs::Header_<ContainerAllocator>  _header_type;
  _header_type header;

   typedef float _position_type;
  _position_type position;

   typedef float _speed_type;
  _speed_type speed;

   typedef std::vector<uint32_t, typename ContainerAllocator::template rebind<uint32_t>::other >  _camera1d_type;
  _camera1d_type camera1d;




  typedef boost::shared_ptr< ::styx_msgs::CarState_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::styx_msgs::CarState_<ContainerAllocator> const> ConstPtr;

}; // struct CarState_

typedef ::styx_msgs::CarState_<std::allocator<void> > CarState;

typedef boost::shared_ptr< ::styx_msgs::CarState > CarStatePtr;
typedef boost::shared_ptr< ::styx_msgs::CarState const> CarStateConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::styx_msgs::CarState_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::styx_msgs::CarState_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace styx_msgs

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'HasHeader': True, 'IsFixedSize': False, 'IsMessage': True}
// {'sensor_msgs': ['/opt/ros/kinetic/share/sensor_msgs/cmake/../msg'], 'std_msgs': ['/opt/ros/kinetic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/kinetic/share/geometry_msgs/cmake/../msg'], 'styx_msgs': ['/home/kvasnyj/Dropbox/carla/catkin_ws/src/styx_msgs/msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__dir__', '__doc__', '__eq__', '__format__', '__ge__', '__getattribute__', '__gt__', '__hash__', '__init__', '__le__', '__lt__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::CarState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::styx_msgs::CarState_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::CarState_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::styx_msgs::CarState_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::CarState_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::styx_msgs::CarState_<ContainerAllocator> const>
  : TrueType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::styx_msgs::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "5f5ce100f2337443c1c11d6317e57dfc";
  }

  static const char* value(const ::styx_msgs::CarState_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x5f5ce100f2337443ULL;
  static const uint64_t static_value2 = 0xc1c11d6317e57dfcULL;
};

template<class ContainerAllocator>
struct DataType< ::styx_msgs::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "styx_msgs/CarState";
  }

  static const char* value(const ::styx_msgs::CarState_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::styx_msgs::CarState_<ContainerAllocator> >
{
  static const char* value()
  {
    return "Header header\n\
float32 position\n\
float32 speed\n\
uint32[] camera1d\n\
================================================================================\n\
MSG: std_msgs/Header\n\
# Standard metadata for higher-level stamped data types.\n\
# This is generally used to communicate timestamped data \n\
# in a particular coordinate frame.\n\
# \n\
# sequence ID: consecutively increasing ID \n\
uint32 seq\n\
#Two-integer timestamp that is expressed as:\n\
# * stamp.sec: seconds (stamp_secs) since epoch (in Python the variable is called 'secs')\n\
# * stamp.nsec: nanoseconds since stamp_secs (in Python the variable is called 'nsecs')\n\
# time-handling sugar is provided by the client library\n\
time stamp\n\
#Frame this data is associated with\n\
# 0: no frame\n\
# 1: global frame\n\
string frame_id\n\
";
  }

  static const char* value(const ::styx_msgs::CarState_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::styx_msgs::CarState_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.header);
      stream.next(m.position);
      stream.next(m.speed);
      stream.next(m.camera1d);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct CarState_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::styx_msgs::CarState_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::styx_msgs::CarState_<ContainerAllocator>& v)
  {
    s << indent << "header: ";
    s << std::endl;
    Printer< ::std_msgs::Header_<ContainerAllocator> >::stream(s, indent + "  ", v.header);
    s << indent << "position: ";
    Printer<float>::stream(s, indent + "  ", v.position);
    s << indent << "speed: ";
    Printer<float>::stream(s, indent + "  ", v.speed);
    s << indent << "camera1d[]" << std::endl;
    for (size_t i = 0; i < v.camera1d.size(); ++i)
    {
      s << indent << "  camera1d[" << i << "]: ";
      Printer<uint32_t>::stream(s, indent + "  ", v.camera1d[i]);
    }
  }
};

} // namespace message_operations
} // namespace ros

#endif // STYX_MSGS_MESSAGE_CARSTATE_H
